# Generated by Django 5.0.2 on 2024-03-01 08:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='has_access',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
